name: cdvae-action

on:
  repository_dispatch:
    types: [build]
  schedule:
    - cron: "0 0 * * *"
  push:
  pull_request:

jobs:
  build:
    env:
      CONDA_PREFIX: /usr/share/miniconda/

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Setup
      shell: bash -l {0}
      run: |
        mkdir WABDB
        mkdir HYDRA_JOBS
        conda env create -n cdvae --file env.ci.yml
        conda activate cdvae
        pip install -e .
        pip install p-tqdm flake8 pytest pycodestyle pydocstyle codecov pytest-cov coverage
        echo 'PIP freeze'
        pip freeze
        echo $PWD
        export HYDRA_FULL_ERROR=1
        export PROJECT_ROOT=$PWD
        export WABDB=$PWD/WABDB 
        export WABDB_DIR=$PWD/WABDB
        export HYDRA_JOBS=$PWD/HYDRA_JOBS
        coverage run -m pytest
        coverage report -m -i
        codecov
        #codecov --token="b61081a0-39de-44a8-8a9c-97d4be82af6d"
        #python cdvae/run.py data=carbon expname=carbon
        # python cdvae/run.py data=perov expname=perov model.predict_property=True
      
